name: Core CI Checks

on:
  workflow_call:

jobs:
  core-checks:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Clean install dependencies. Fail on lockfile Changes.
        run: yarn install --immutable --immutable-cache --check-cache --non-interactive

      - name: Prettier
        run: yarn prettier

      - name: ESLint
        run: yarn eslint

      - name: Tests
        run: yarn test:int

      # Not sure why, but setting `devtool: false` in `webpack.prod.js` with no increased memory gives
      # Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
      #
      # Increase memory with https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes
      - name: Build smoke check package
        run: yarn package
        # env:
        #   NODE_OPTIONS: --max_old_space_size=4096
